import { ReactNode } from "react";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";

interface RootLayoutProps {
  children: ReactNode;
}

const inter = Inter({ subsets: ["latin"] });

{
  /*export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    url: "https://link-preview-eta.vercel.app/",
    images: "https://link-preview-eta.vercel.app/assets/header.png",
  },
};*/
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <>
      <html lang="en">
        <head>
          <meta property="og:title" content="Link Preview" />
          <meta property="og:description" content="Link preview page" />
          <meta
            property="og:url"
            content="https://link-preview-eta.vercel.app/"
          />
          <meta
            property="og:image"
            content="https://link-preview-eta.vercel.app/assets/header.png"
          />
          <meta property="og:type" content="website" />
        </head>

        <body className={inter.className}>{children}</body>
      </html>
    </>
  );
}
